/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import estructural.Funcion;
import estructural.Reserva;
import estructural.Tarjeta;
import estructural.Teatro;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Paleox
 */
public class InterfazCancelarReserva extends javax.swing.JFrame {  

    /**
     * Creates new form InterfazCancelarReserva
     *
     * @param teatro
     */
    
    private Teatro teatro;
    private Tarjeta tarjeta;
    
    public InterfazCancelarReserva(Teatro teatro, Tarjeta tarjeta) {
        this.teatro = teatro;
        this.tarjeta = tarjeta;
        initComponents();
        popularTarjetas();
    }

    public void popularTarjetas() {
        if(this.tarjeta.getTipo() == 3){
            cbTarjetas.addItem(this.tarjeta.getDocumento());
            cbTarjetas.setEnabled(false);
        }else{
            ArrayList<Tarjeta> tarjetas = teatro.getTarjetas();

            for (Tarjeta tarjeta : tarjetas) {
                if(tarjeta.getTipo() == 3){
                    cbTarjetas.addItem(tarjeta.getDocumento());
                }
                
            }        
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbTarjetas = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cbReservas = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        txtFuncionReserva = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPeliculaFuncion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSalaReserva = new javax.swing.JTextField();
        btnCancelarReserva = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cancelar Reserva");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Tarjeta:");

        cbTarjetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTarjetasActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Reserva:");

        cbReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbReservasActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Función:");

        txtFuncionReserva.setEditable(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Película:");

        txtPeliculaFuncion.setEditable(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Sala:");

        txtSalaReserva.setEditable(false);

        btnCancelarReserva.setText("Cancelar");
        btnCancelarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarReservaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cbTarjetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbReservas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPeliculaFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFuncionReserva)
                            .addComponent(txtSalaReserva, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)))
                    .addComponent(btnCancelarReserva, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(75, 126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbTarjetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbReservas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSalaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFuncionReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPeliculaFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(btnCancelarReserva)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbTarjetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTarjetasActionPerformed
        // TODO add your handling code here:
        if (cbReservas.getItemCount() > 0) {
            cbReservas.removeAllItems();
        }
        ArrayList<Reserva> reservas = teatro.getReservasTarjeta(cbTarjetas.getSelectedItem().toString());
        if (!reservas.isEmpty()) {
            for (Reserva reserva : reservas) {
                cbReservas.addItem(reserva.getCodigo());
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "La tarjeta no posee reservas", "ERROR!", JOptionPane.ERROR_MESSAGE);
            txtSalaReserva.setText("");
            txtFuncionReserva.setText("");
            txtPeliculaFuncion.setText("");
        }
    }//GEN-LAST:event_cbTarjetasActionPerformed

    private void cbReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbReservasActionPerformed
        // TODO add your handling code here:        
        if (cbReservas.getItemCount() > 0) {            
            btnCancelarReserva.setEnabled(true);            
            Funcion funcion = teatro.getFuncionReserva(Integer.parseInt(cbReservas.getSelectedItem().toString()));
            txtSalaReserva.setText("" + funcion.getSala().getCodigo());
            txtFuncionReserva.setText("" + funcion.getFecha());
            txtPeliculaFuncion.setText(funcion.getPelicula().getTitulo());            
        } else {
            btnCancelarReserva.setEnabled(false);
        }
    }//GEN-LAST:event_cbReservasActionPerformed

    private void btnCancelarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarReservaActionPerformed
        // TODO add your handling code here:        
        Reserva reserva = teatro.getReserva(Integer.parseInt(cbReservas.getSelectedItem().toString()));
        if (reserva.getEstado() == 1) { 
            int codReserva = Integer.parseInt(cbReservas.getSelectedItem().toString());
            teatro.cancelarReserva(codReserva);
            JOptionPane.showMessageDialog(rootPane, "Reserva cancelada correctamente!",
                    "Confirmacion", JOptionPane.INFORMATION_MESSAGE);            
            cbTarjetasActionPerformed(evt);            
            txtSalaReserva.setText("");
            txtFuncionReserva.setText("");
            txtPeliculaFuncion.setText("");
            cbReservasActionPerformed(evt);
        } else {
            JOptionPane.showMessageDialog(rootPane, "La reserva ya fue pagada", "ERROR!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCancelarReservaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarReserva;
    private javax.swing.JComboBox cbReservas;
    private javax.swing.JComboBox cbTarjetas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtFuncionReserva;
    private javax.swing.JTextField txtPeliculaFuncion;
    private javax.swing.JTextField txtSalaReserva;
    // End of variables declaration//GEN-END:variables
}
