/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import estructural.Funcion;
import estructural.MyJPanel;
import estructural.Reserva;
import estructural.Sala;
import estructural.Silla;
import estructural.Tarjeta;
import estructural.Teatro;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author Paleox
 */
public class InterfazCrearReserva extends javax.swing.JFrame {

    /**
     * Creates new form InterfazRegistrarReserva
     */
    
    private Teatro teatro;
    private Tarjeta tarjeta;
    private int sillasReservas;

    public InterfazCrearReserva(Teatro teatro, Tarjeta tarjeta) {
        this.teatro = teatro;
        this.tarjeta = tarjeta;
        initComponents();
        popularTarjetas();
        popularFunciones();
        txtCodigoReserva.setText("" + teatro.getCodigoReserva());
    }
    
    public void popularTarjetas(){
        if(this.tarjeta.getTipo() == 3){
            cbTarjetas.addItem(this.tarjeta.getDocumento());
            cbTarjetas.setEnabled(false);
        }else{
            ArrayList<Tarjeta> tarjetas = teatro.getTarjetas();

            for(Tarjeta tarjeta: tarjetas){
                if(tarjeta.getTipo() == 3){
                    cbTarjetas.addItem(tarjeta.getDocumento());
                }
            }
        }
        
    }
    
    public void popularFunciones(){
        ArrayList<Funcion> funciones = teatro.getFunciones();

        for(Funcion funcion: funciones){
            cbFunciones.addItem(funcion.getCodigo());
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbTarjetas = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cbFunciones = new javax.swing.JComboBox();
        lblFuncion = new javax.swing.JLabel();
        jpContenedor1 = new javax.swing.JPanel();
        btnRegistrarReserva = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtCodigoReserva = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Reserva");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Tarjeta:");

        cbTarjetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTarjetasActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Función:");

        cbFunciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFuncionesActionPerformed(evt);
            }
        });

        jpContenedor1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpContenedor1Layout = new javax.swing.GroupLayout(jpContenedor1);
        jpContenedor1.setLayout(jpContenedor1Layout);
        jpContenedor1Layout.setHorizontalGroup(
            jpContenedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpContenedor1Layout.setVerticalGroup(
            jpContenedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 254, Short.MAX_VALUE)
        );

        btnRegistrarReserva.setText("Reservar");
        btnRegistrarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarReservaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Código Reserva:");

        txtCodigoReserva.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpContenedor1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRegistrarReserva))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbTarjetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCodigoReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 205, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbFunciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblFuncion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCodigoReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbTarjetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(cbFunciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jpContenedor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegistrarReserva)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbTarjetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTarjetasActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbTarjetasActionPerformed

    private void cbFuncionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFuncionesActionPerformed
        // TODO add your handling code here:
        Funcion funcion = teatro.getFuncion(Integer.parseInt(cbFunciones.getSelectedItem().toString()));
        lblFuncion.setText(funcion.getSala().getCodigo() + " - " + funcion.getPelicula().getTitulo() + " - " + funcion.getFecha());
        
        dibujarSillas(funcion);
        validarReservadas(funcion);
    }//GEN-LAST:event_cbFuncionesActionPerformed

    private void btnRegistrarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarReservaActionPerformed
        // TODO add your handling code here:
        
        ArrayList<Silla> sillas = new ArrayList<>();
        
        for(Component component: jpContenedor1.getComponents()){
            if(component.getBackground() == Color.yellow){
                MyJPanel jp =(MyJPanel)component;
                sillas.add(jp.getSilla());
            }
        }
        
        if(!sillas.isEmpty()){
            Funcion funcion = teatro.getFuncion(Integer.parseInt(cbFunciones.getSelectedItem().toString()));
            Tarjeta tarj = teatro.getTarjeta(cbTarjetas.getSelectedItem().toString());
            teatro.crearReserva(funcion, tarj, sillas);

            JOptionPane.showMessageDialog(rootPane, "Reserva registrada correctamente!", 
            "Confirmacion", JOptionPane.INFORMATION_MESSAGE);

            txtCodigoReserva.setText("" + teatro.getCodigoReserva());
            dibujarSillas(teatro.getFuncion(Integer.parseInt(cbFunciones.getSelectedItem().toString())));
        }else{
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar sillas para reservar.", "ERROR!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRegistrarReservaActionPerformed

    public void dibujarSillas(Funcion funcion){
        this.sillasReservas = 0;
        Sala sala = funcion.getSala();
        
        jpContenedor1.removeAll();
        jpContenedor1.repaint();
        jpContenedor1.setBackground(Color.white);
        int ancho = jpContenedor1.getWidth();
        int alto = jpContenedor1.getHeight();
        
        int anchoSilla = ancho / sala.getColumnas();
        int altoSilla = alto / sala.getFilas();
        
        int x, y;
        x = 0;
        y = 0;
        
        for(int i = 1; i <= sala.getColumnas(); i++){
            for(int j = 1; j <= sala.getFilas(); j++){
                MyJPanel jp = new MyJPanel();
                jp.setSize(anchoSilla, altoSilla);
                jp.setLocation(x, y);
                jp.setBorder(BorderFactory.createLineBorder(Color.black));
                jp.setSilla(sala.getSilla(i,j));
                
                switch(jp.getSilla().getTipo()){
                    case 1:
                        jp.setBackground(Color.gray);
                        break;
                    case 2:
                        jp.setBackground(Color.blue);
                        break;
                }
                
                Reserva reserva = teatro.getReserva(funcion,i,j);
                if(reserva != null){
                    this.sillasReservas++;
                    switch(reserva.getEstado()){
                        case 1:
                            jp.setBackground(Color.red);
                            break;
                        case 2:
                            jp.setBackground(Color.black);
                            break;
                        case 3:
                            break;
                    }
                }
                
                if(!(jp.getBackground() == Color.red || jp.getBackground() == Color.black)){
                    jp.addMouseListener(new MouseAdapter() { 
                    @Override
                    public void mousePressed(MouseEvent me) {
                        MyJPanel jp = (MyJPanel) me.getSource();
                        int numcol = jp.getSilla().getNumeroColumna();
                        int numfil = jp.getSilla().getNumeroFila();
                        
                        if(jp.getBackground() != Color.yellow){
                            jp.setBackground(Color.yellow);
                        }else{
                            switch(jp.getSilla().getTipo()){
                                case 1:
                                    jp.setBackground(Color.gray);
                                     break;
                                case 2:
                                    jp.setBackground(Color.blue);
                                    break;
                            } 
                        }
                    }}); 
                }
                
                
                jpContenedor1.add(jp);
                x += anchoSilla;
            }
            y += altoSilla;
            x = 0;
        }
    }
    
    public void validarReservadas(Funcion funcion){
        btnRegistrarReserva.setEnabled(true);
        Sala sala = funcion.getSala();        
        int totalSillas = sala.getSillas().size();        
        if(totalSillas == this.sillasReservas){
            this.sillasReservas = 0;
            JOptionPane.showMessageDialog(rootPane, "Todas las sillas estan reservadas para esta función", "Advertencia", JOptionPane.ERROR_MESSAGE);
            btnRegistrarReserva.setEnabled(false);
        }        
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarReserva;
    private javax.swing.JComboBox cbFunciones;
    private javax.swing.JComboBox cbTarjetas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jpContenedor1;
    private javax.swing.JLabel lblFuncion;
    private javax.swing.JTextField txtCodigoReserva;
    // End of variables declaration//GEN-END:variables
}
