/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import estructural.MyJPanel;
import estructural.Sala;
import estructural.Teatro;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.BorderFactory;

/**
 *
 * @author Paleox
 */
public class InterfazConfigurarSilla extends javax.swing.JFrame {

    /**
     * Creates new form InterfazConfigurarSilla
     */
        
    private Teatro teatro;
    
    public InterfazConfigurarSilla(Teatro teatro) {
        this.teatro = teatro;
        initComponents();
        popularSalas();
    }
    
    public void popularSalas(){
        ArrayList<Sala> salas = teatro.getSalas();
        
        for(Sala sala: salas){
            cbSalas.addItem(sala.getCodigo());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbSalas = new javax.swing.JComboBox();
        jpContenedor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configurar Silla");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Sala: ");

        cbSalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSalasActionPerformed(evt);
            }
        });

        jpContenedor.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpContenedorLayout = new javax.swing.GroupLayout(jpContenedor);
        jpContenedor.setLayout(jpContenedorLayout);
        jpContenedorLayout.setHorizontalGroup(
            jpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpContenedorLayout.setVerticalGroup(
            jpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 247, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbSalas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 312, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbSalas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbSalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSalasActionPerformed

        jpContenedor.removeAll();
        jpContenedor.repaint();
        jpContenedor.setBackground(Color.white);
        int ancho = jpContenedor.getWidth();
        int alto = jpContenedor.getHeight();
        
        
        final Sala sala;
        int codSala = Integer.parseInt(cbSalas.getSelectedItem().toString());
        sala = teatro.getSala(codSala);
        
        int anchoSilla = ancho / sala.getColumnas();
        int altoSilla = alto / sala.getFilas();
        
        int x, y;
        x = 0;
        y = 0;
        
        for(int i = 1; i <= sala.getColumnas(); i++){
            for(int j = 1; j <= sala.getFilas(); j++){
                MyJPanel jp = new MyJPanel();
                jp.setSize(anchoSilla, altoSilla);
                jp.setLocation(x, y);
                jp.setBorder(BorderFactory.createLineBorder(Color.black));
                jp.setSilla(sala.getSilla(i,j));
                
                switch(jp.getSilla().getTipo()){
                    case 1:
                        jp.setBackground(Color.gray);
                        break;
                    case 2:
                        jp.setBackground(Color.blue);
                        break;
                }
                
                jp.addMouseListener(new MouseAdapter() { 
                    @Override
                    public void mousePressed(MouseEvent me) {
                        MyJPanel jp = (MyJPanel) me.getSource();
                        int numCol = jp.getSilla().getNumeroColumna();
                        int numFil = jp.getSilla().getNumeroFila();

                        switch(jp.getSilla().getTipo()){
                            case 1:
                                jp.setBackground(Color.blue);
                                teatro.configurarSilla(sala.getCodigo(), numCol, numFil, 2);
                                break;
                            case 2:
                                jp.setBackground(Color.gray);
                                teatro.configurarSilla(sala.getCodigo(), numCol, numFil, 1);
                                break;
                        }
                    }
                }); 
                
                
                jpContenedor.add(jp);
                x += anchoSilla;
            }
            y += altoSilla;
            x = 0;
        }
    }//GEN-LAST:event_cbSalasActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbSalas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jpContenedor;
    // End of variables declaration//GEN-END:variables
}
