/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import estructural.Tarjeta;
import estructural.Teatro;
import javax.swing.JOptionPane;

/**
 *
 * @author Paleox
 */
public class InterfazPrincipal extends javax.swing.JFrame {
    
    /**
     * Creates new form InterfazPrincipal
     * @param teatro
     * @param tarjeta
     */
    
    private Teatro teatro;
    private Tarjeta tarjeta;
    
    public InterfazPrincipal(Teatro teatro, Tarjeta tarjeta) {
        this.teatro = teatro;
        this.tarjeta = tarjeta;
        initComponents();
        setLocationRelativeTo(null);
        validarPermisos();
    }
    
    public void validarPermisos(){
        switch(this.tarjeta.getTipo()){
            case 3:
                jmTeatro.setEnabled(false);
                jmTarjeta.setEnabled(false);
                jmVenta.setEnabled(false);
                lblStatus.setText("<html>Usuario: <strong><span>"+ tarjeta.getDocumento() +"</span></strong>");
                break;
            case 2:
                jmTeatro.setEnabled(false);
                lblStatus.setText("<html>Usuario: <strong><span style='color:blue'>"+ tarjeta.getDocumento() +"</span></strong>");
                break;
            case 1:
                lblStatus.setText("<html>Usuario: <strong><span style='color:red'>"+ tarjeta.getDocumento() +"</span></strong>");
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmArchivo = new javax.swing.JMenu();
        jmSalir = new javax.swing.JMenuItem();
        jmTeatro = new javax.swing.JMenu();
        jmRegistrarPelicula = new javax.swing.JMenuItem();
        jmCrearSala = new javax.swing.JMenuItem();
        jmConfigurarSilla = new javax.swing.JMenuItem();
        jmCrearFuncion = new javax.swing.JMenuItem();
        jmTarjeta = new javax.swing.JMenu();
        jmRegistrarTarjeta = new javax.swing.JMenuItem();
        jmRecargarTarjeta = new javax.swing.JMenuItem();
        jmReserva = new javax.swing.JMenu();
        jmRegistrarReserva = new javax.swing.JMenuItem();
        jmCancelarReserva = new javax.swing.JMenuItem();
        jmVenta = new javax.swing.JMenu();
        jmRegistrarVenta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Teatro - Menú Principal");
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/theatre.png"))); // NOI18N

        jmArchivo.setText("Archivo");

        jmSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salir.png"))); // NOI18N
        jmSalir.setText("Salir");
        jmSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSalirActionPerformed(evt);
            }
        });
        jmArchivo.add(jmSalir);

        jMenuBar1.add(jmArchivo);

        jmTeatro.setText("Teatro");

        jmRegistrarPelicula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pelicula.png"))); // NOI18N
        jmRegistrarPelicula.setText("Registrar Pelicula");
        jmRegistrarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmRegistrarPeliculaActionPerformed(evt);
            }
        });
        jmTeatro.add(jmRegistrarPelicula);

        jmCrearSala.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sala.png"))); // NOI18N
        jmCrearSala.setText("Crear Sala");
        jmCrearSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCrearSalaActionPerformed(evt);
            }
        });
        jmTeatro.add(jmCrearSala);

        jmConfigurarSilla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/silla.png"))); // NOI18N
        jmConfigurarSilla.setText("Configurar Silla");
        jmConfigurarSilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmConfigurarSillaActionPerformed(evt);
            }
        });
        jmTeatro.add(jmConfigurarSilla);

        jmCrearFuncion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/funcion.png"))); // NOI18N
        jmCrearFuncion.setText("Crear Función");
        jmCrearFuncion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCrearFuncionActionPerformed(evt);
            }
        });
        jmTeatro.add(jmCrearFuncion);

        jMenuBar1.add(jmTeatro);

        jmTarjeta.setText("Tarjeta");

        jmRegistrarTarjeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tarjeta.png"))); // NOI18N
        jmRegistrarTarjeta.setText("Registrar Tarjeta");
        jmRegistrarTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmRegistrarTarjetaActionPerformed(evt);
            }
        });
        jmTarjeta.add(jmRegistrarTarjeta);

        jmRecargarTarjeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/recargar.png"))); // NOI18N
        jmRecargarTarjeta.setText("Recargar Tarjeta");
        jmRecargarTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmRecargarTarjetaActionPerformed(evt);
            }
        });
        jmTarjeta.add(jmRecargarTarjeta);

        jMenuBar1.add(jmTarjeta);

        jmReserva.setText("Reserva");

        jmRegistrarReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/registrar.png"))); // NOI18N
        jmRegistrarReserva.setText("Registrar Reserva");
        jmRegistrarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmRegistrarReservaActionPerformed(evt);
            }
        });
        jmReserva.add(jmRegistrarReserva);

        jmCancelarReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        jmCancelarReserva.setText("Cancelar Reserva");
        jmCancelarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCancelarReservaActionPerformed(evt);
            }
        });
        jmReserva.add(jmCancelarReserva);

        jMenuBar1.add(jmReserva);

        jmVenta.setText("Venta");

        jmRegistrarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/venta.png"))); // NOI18N
        jmRegistrarVenta.setText("Registrar Venta");
        jmRegistrarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmRegistrarVentaActionPerformed(evt);
            }
        });
        jmVenta.add(jmRegistrarVenta);

        jMenuBar1.add(jmVenta);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmRegistrarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmRegistrarPeliculaActionPerformed
        // TODO add your handling code here:
        InterfazRegistarPelicula interfazRegistrarPelicula = new InterfazRegistarPelicula(teatro);
        interfazRegistrarPelicula.setLocationRelativeTo(null);
        interfazRegistrarPelicula.setVisible(true);
    }//GEN-LAST:event_jmRegistrarPeliculaActionPerformed

    private void jmCrearSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCrearSalaActionPerformed
        // TODO add your handling code here:
        InterfazCrearSala interfazCrearSala = new InterfazCrearSala(teatro);
        interfazCrearSala.setLocationRelativeTo(null);
        interfazCrearSala.setVisible(true);
    }//GEN-LAST:event_jmCrearSalaActionPerformed

    private void jmConfigurarSillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmConfigurarSillaActionPerformed
        // TODO add your handling code here:
        InterfazConfigurarSilla interfazConfigurarSilla = new InterfazConfigurarSilla(teatro);
        interfazConfigurarSilla.setLocationRelativeTo(null);
        interfazConfigurarSilla.setVisible(true);
    }//GEN-LAST:event_jmConfigurarSillaActionPerformed

    private void jmCrearFuncionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCrearFuncionActionPerformed
        // TODO add your handling code here:
        InterfazCrearFuncion interfazCrearFuncion = new InterfazCrearFuncion(teatro);
        interfazCrearFuncion.setLocationRelativeTo(null);
        interfazCrearFuncion.setVisible(true);
    }//GEN-LAST:event_jmCrearFuncionActionPerformed

    private void jmRegistrarTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmRegistrarTarjetaActionPerformed
        // TODO add your handling code here:
        InterfazRegistrarTarjeta interfazRegistrarTarjeta = new InterfazRegistrarTarjeta(teatro);
        interfazRegistrarTarjeta.setLocationRelativeTo(null);
        interfazRegistrarTarjeta.setVisible(true);
    }//GEN-LAST:event_jmRegistrarTarjetaActionPerformed

    private void jmRecargarTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmRecargarTarjetaActionPerformed
        // TODO add your handling code here:
        InterfazRecargarTarjeta interfazRecargarTarjeta = new InterfazRecargarTarjeta(teatro);
        interfazRecargarTarjeta.setLocationRelativeTo(null);
        interfazRecargarTarjeta.setVisible(true);
    }//GEN-LAST:event_jmRecargarTarjetaActionPerformed

    private void jmRegistrarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmRegistrarReservaActionPerformed
        // TODO add your handling code here:
        InterfazCrearReserva interfazRegistrarReserva = new InterfazCrearReserva(teatro, tarjeta);
        interfazRegistrarReserva.setLocationRelativeTo(null);
        interfazRegistrarReserva.setVisible(true);
    }//GEN-LAST:event_jmRegistrarReservaActionPerformed

    private void jmCancelarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCancelarReservaActionPerformed
        // TODO add your handling code here:
        InterfazCancelarReserva interfazCancelarReserva = new InterfazCancelarReserva(teatro, tarjeta);
        interfazCancelarReserva.setLocationRelativeTo(null);
        interfazCancelarReserva.setVisible(true);
    }//GEN-LAST:event_jmCancelarReservaActionPerformed

    private void jmRegistrarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmRegistrarVentaActionPerformed
        // TODO add your handling code here:
        if(teatro.getFunciones().isEmpty()){
            JOptionPane.showMessageDialog(this, "Debe registrar funciones antes de registrar una venta", 
                    "No Existen funciones registradas", JOptionPane.ERROR_MESSAGE);
        }else{
            InterfazRegistrarVenta interfazRegistrarVenta = new InterfazRegistrarVenta(teatro);
            interfazRegistrarVenta.setLocationRelativeTo(null);
            interfazRegistrarVenta.setVisible(true);
        }
        
    }//GEN-LAST:event_jmRegistrarVentaActionPerformed

    private void jmSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jmSalirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmArchivo;
    private javax.swing.JMenuItem jmCancelarReserva;
    private javax.swing.JMenuItem jmConfigurarSilla;
    private javax.swing.JMenuItem jmCrearFuncion;
    private javax.swing.JMenuItem jmCrearSala;
    private javax.swing.JMenuItem jmRecargarTarjeta;
    private javax.swing.JMenuItem jmRegistrarPelicula;
    private javax.swing.JMenuItem jmRegistrarReserva;
    private javax.swing.JMenuItem jmRegistrarTarjeta;
    private javax.swing.JMenuItem jmRegistrarVenta;
    private javax.swing.JMenu jmReserva;
    private javax.swing.JMenuItem jmSalir;
    private javax.swing.JMenu jmTarjeta;
    private javax.swing.JMenu jmTeatro;
    private javax.swing.JMenu jmVenta;
    private javax.swing.JLabel lblStatus;
    // End of variables declaration//GEN-END:variables
}
